version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://:myawesomepassword@redis:6379/0
      - CELERY_BROKER_URL=redis://:myawesomepassword@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:myawesomepassword@redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass myawesomepassword

  celery:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://:myawesomepassword@redis:6379/0
      - CELERY_BROKER_URL=redis://:myawesomepassword@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:myawesomepassword@redis:6379/0
    command: python -m celery -A app.celery_app worker --loglevel=info

  celery-beat:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://:myawesomepassword@redis:6379/0
      - CELERY_BROKER_URL=redis://:myawesomepassword@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:myawesomepassword@redis:6379/0
    command: python -m celery -A app.celery_app beat --loglevel=info

  flower:
    build: .
    ports:
      - "5555:5555"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://:myawesomepassword@redis:6379/0
      - CELERY_BROKER_URL=redis://:myawesomepassword@redis:6379/0
    command: python -m celery -A app.celery_app flower

volumes:
  postgres_data: